### ISSUE TITLE
MultiGPU Out Of Memory, no matter how I set the batch size.

### ISSUE THREAD

**Issue by wunengbiao** [mozilla/TTS#548]
git commit :  af6f86252e6fe21fc02357fe681344f89d75a0ca
torch : 1.5.0
tensorflow : 2.3.0
GPU: 4  GTX1080 8GB
Question: when I use 4 GPU, I set the batch size 8, 16, 32, but  error out of memory occur .

**Comment by erogol** [comment]
how long is the longest sample in your dataset?

**Comment by wunengbiao** [comment]
> how long is the longest sample in your dataset?

I use the LJSpeech Dataset.

**Comment by erogol** [comment]
how do you run the training?

**Comment by wunengbiao** [comment]
python TTS/bin/distribute.py --config_path config.json --script train_tts.py > train.log 2>&1 &

**Comment by wunengbiao** [comment]
> how do you run the training?

python TTS/bin/distribute.py --config_path config.json --script train_tts.py > train.log 2>&1 &

**Comment by erogol** [comment]
and your config.json?

**Comment by erogol** [comment]
are you sure it uses GPUs ?Have you checked nvidia-smi?

**Comment by erogol** [comment]
what is your pytorch version ?

**Comment by wunengbiao** [comment]
> are you sure it uses GPUs ?Have you checked nvidia-smi?

yes, epoch 0 is successful, but epoch 1 error occur.

**Comment by wunengbiao** [comment]
> what is your pytorch version ?

I have try 1.5 and 1.6.

**Comment by erogol** [comment]
try dev branch and try to enable ```"apex_amp_level": "O1", ```

**Comment by wunengbiao** [comment]
`        grid_x, grid_y = torch.meshgrid(torch.arange(olen, device=olen.device), torch.arange(ilen, device=ilen.device))
`
error occur, fix like this can solve.

torch 1.6
cuda 10.2
can solve error while using gpu.
thank you very much!

**Comment by erogol** [comment]
interesting! I don't see how it solves the issue but happy that it is solved.
